<h1>
 Title: Reading Error for Changetime
</h1>
<h3>
 Author: Anonymous
</h3>
<h3>
 Date: 2021-05-13T02:07:26.394455+10:00
</h3>
<h3>
 Category: Assignments
</h3>
<h3>
 Vote Count: 0
</h3>
<p>
 Running test_course_changetime
</p>
<p>
 Traceback (most recent call last):
</p>
<p>
 File "schedule_tests.py", line 297, in &lt;module&gt;
</p>
<p>
 testfn() # Adding the parentheses calls whatever testfn is
</p>
<p>
 File "schedule_tests.py", line 252, in test_course_changetime
</p>
<p>
 my_schedule.warnings)
</p>
<p>
 AssertionError: my_schedule warnings list should be ['ARCH 1120 STU 520: time changed from TBA to MWF 8:00am-8:00pm', 'ARCH 1120 STU 520: time change causes conflict with AEP 3560 LEC 001', 'ARCH 1120 STU 520: time change causes conflict with FAKER 0000 LEC 002'], but is ['ARCH 1120 STU 520: time changed from TBA to MWF 8:00am-8:00pm', 'ARCH 1120 STU 520 : time change causes conflict with AEP 3560 LEC 001', 'ARCH 1120 STU 520 : time change causes conflict with FAKER 0000 LEC 002']
</p>
<p>
 To me, these look like the same messages. Could someone help me understand why this would throw an error?
</p>
<h3>
 ----------- REPLIES -----------
</h3>
<div style="text-indent: 2em;">
 <h3>
  Author: Prof. Lee (she/they) (admin)
 </h3>
 <h3>
  Vote Count: 0
 </h3>
 <p>
  It looks like there's a space after the colon after "520"; I think that's the problem.
 </p>
 <h3>
  ------------------------------------
 </h3>
</div>